apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-project
  template:
    metadata:
      labels:
        app: k8s-project
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo '<!DOCTYPE html>
          <html>
          <head><title>Welcome to Ganesh Database</title></head>
          <body>
          <h1 style="color:blue; text-align:center;">Welcome to Ganesh Database</h1>
          <p style="text-align:center;">This is a Kubernetes project serving static content.</p>
          </body>
          </html>' > /usr/share/nginx/html/index.html &&
          nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-project
spec:
  selector:
    app: k8s-project
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
